x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  nopcommerce_web:
    build: .
    container_name: nopcommerce
    ports:
      - "80:80"
    depends_on:
      - nopcommerce_database
      - otel-collector
    volumes:
      - nopcommerce_app_data:/app/App_Data
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    logging: *logging

  nopcommerce_database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: nopcommerce_mssql_server
    environment:
      SA_PASSWORD: "nopCommerce_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - nopcommerce_data:/var/opt/mssql
    logging: *logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector/config.yml"]
    volumes:
      - ./src/otel-collector/config.yml:/etc/otel-collector/config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
      - prometheus
    restart: unless-stopped
    logging: *logging

  jaeger:
    image: jaegertracing/all-in-one:1.60.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317"
    restart: unless-stopped
    logging: *logging

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=7d
      - --web.enable-lifecycle
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./src/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    restart: unless-stopped
    logging: *logging

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger
    restart: unless-stopped
    logging: *logging

volumes:
  nopcommerce_data:
  nopcommerce_app_data: