{
 "title": "AS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (product_name) (\n  increase(inventory_update_duration_milliseconds_sum[6h])\n)\n/\nsum by (product_name) (\n  increase(inventory_update_duration_milliseconds_count[6h])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Order Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (\n  sum(rate(orders_placed_total{order_status=\"failure\"}[5m])) or vector(0)\n)\n/ sum(rate(orders_placed_total[5m]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Order Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (payment_method, order_status) (rate(orders_placed_total[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Infrastructure & Dependencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Payment Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (payment_method) (rate(payment_provider_duration_milliseconds_sum[5m])) \n/ \nsum by (payment_method) (rate(payment_provider_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Distributed Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "service": "NopCommerce.Web" }
   ]
  }
 ]
}